trigger:
  branches:
    include:
      - main

stages:
  - stage: create_infra
    jobs:
      - job: createinfra
        pool:
          name: 'argocd'

        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
        - script: ls
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'argocd'
            KeyVaultName: 'argocd'
            SecretsFilter: '*'
            RunAsPreJob: true
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'argocd'
            ScriptType: 'FilePath'
            ScriptPath: './script.ps1'
            ScriptArguments: '-argocdTenant "$(argocdTenant)" -argocdSecret "$(argocdSecret)" -argocdAppId "$(argocdAppId)"'
            azurePowerShellVersion: 'LatestVersion'
